export const sortCardsFunction = (card1: Card, card2: Card) => card1.ranking - card2.ranking

export const ALL_CARDS: Card[] = [
    { id: "1-ace clubs",  "suite":"clubs", "rank":"ace",    "name":"ace clubs","img":"cards-front/clubs_ace.svg","ranking":1,"value":1 },
    { id: "1-2 clubs",  "suite":"clubs", "rank":"2",      "name":"2 clubs","img":"cards-front/clubs_2.svg","ranking":2,"value":2 },
    { id: "1-3 clubs",  "suite":"clubs", "rank":"3",      "name":"3 clubs","img":"cards-front/clubs_3.svg","ranking":3,"value":3 },
    { id: "1-4 clubs",  "suite":"clubs", "rank":"4",      "name":"4 clubs","img":"cards-front/clubs_4.svg","ranking":4,"value":4 },
    { id: "1-5 clubs",  "suite":"clubs", "rank":"5",      "name":"5 clubs","img":"cards-front/clubs_5.svg","ranking":5,"value":5 },
    { id: "1-6 clubs",  "suite":"clubs", "rank":"6",      "name":"6 clubs","img":"cards-front/clubs_6.svg","ranking":6,"value":6 },
    { id: "1-7 clubs",  "suite":"clubs", "rank":"7",      "name":"7 clubs","img":"cards-front/clubs_7.svg","ranking":7,"value":7 },
    { id: "1-8 clubs",  "suite":"clubs", "rank":"8",      "name":"8 clubs","img":"cards-front/clubs_8.svg","ranking":8,"value":8 },
    { id: "1-9 clubs",  "suite":"clubs", "rank":"9",      "name":"9 clubs","img":"cards-front/clubs_9.svg","ranking":9,"value":9 },
    { id: "1-10 clubs",  "suite":"clubs", "rank":"10",     "name":"10 clubs","img":"cards-front/clubs_10.svg","ranking":10,"value":10 },
    { id: "1-jack clubs",  "suite":"clubs", "rank":"jack",   "name":"jack clubs","img":"cards-front/clubs_jack.svg","ranking":11,"value":10 },
    { id: "1-king clubs",  "suite":"clubs", "rank":"king",   "name":"king clubs","img":"cards-front/clubs_king.svg","ranking":12,"value":10 },
    { id: "1-queen clubs",  "suite":"clubs", "rank":"queen",  "name":"queen clubs","img":"cards-front/clubs_queen.svg","ranking":13,"value":10 },
    { id: "1-ace diamonds",  "suite":"diamonds","rank":"ace",  "name":"ace diamonds","img":"cards-front/diamonds_ace.svg","ranking":1,"value":1 },
    { id: "1-2 diamonds",  "suite":"diamonds","rank":"2",    "name":"2 diamonds","img":"cards-front/diamonds_2.svg","ranking":2,"value":2 },
    { id: "1-3 diamonds",  "suite":"diamonds","rank":"3",    "name":"3 diamonds","img":"cards-front/diamonds_3.svg","ranking":3,"value":3 },
    { id: "1-4 diamonds",  "suite":"diamonds","rank":"4",    "name":"4 diamonds","img":"cards-front/diamonds_4.svg","ranking":4,"value":4 },
    { id: "1-5 diamonds",  "suite":"diamonds","rank":"5",    "name":"5 diamonds","img":"cards-front/diamonds_5.svg","ranking":5,"value":5 },
    { id: "1-6 diamonds",  "suite":"diamonds","rank":"6",    "name":"6 diamonds","img":"cards-front/diamonds_6.svg","ranking":6,"value":6 },
    { id: "1-7 diamonds",  "suite":"diamonds","rank":"7",    "name":"7 diamonds","img":"cards-front/diamonds_7.svg","ranking":7,"value":7 },
    { id: "1-8 diamonds",  "suite":"diamonds","rank":"8",    "name":"8 diamonds","img":"cards-front/diamonds_8.svg","ranking":8,"value":8 },
    { id: "1-9 diamonds",  "suite":"diamonds","rank":"9",    "name":"9 diamonds","img":"cards-front/diamonds_9.svg","ranking":9,"value":9 },
    { id: "1-10 diamonds",  "suite":"diamonds","rank":"10",   "name":"10 diamonds","img":"cards-front/diamonds_10.svg","ranking":10,"value":10 },
    { id: "1-jack diamonds",  "suite":"diamonds","rank":"jack", "name":"jack diamonds","img":"cards-front/diamonds_jack.svg","ranking":11,"value":10 },
    { id: "1-king diamonds",  "suite":"diamonds","rank":"king", "name":"king diamonds","img":"cards-front/diamonds_king.svg","ranking":12,"value":10 },
    { id: "1-queen diamonds",  "suite":"diamonds","rank":"queen","name":"queen diamonds","img":"cards-front/diamonds_queen.svg","ranking":13,"value":10 },
    { id: "1-ace hearts",  "suite":"hearts","rank":"ace",    "name":"ace hearts","img":"cards-front/hearts_ace.svg","ranking":1,"value":1 },
    { id: "1-2 hearts",  "suite":"hearts","rank":"2",      "name":"2 hearts","img":"cards-front/hearts_2.svg","ranking":2,"value":2 },
    { id: "1-3 hearts",  "suite":"hearts","rank":"3",      "name":"3 hearts","img":"cards-front/hearts_3.svg","ranking":3,"value":3 },
    { id: "1-4 hearts",  "suite":"hearts","rank":"4",      "name":"4 hearts","img":"cards-front/hearts_4.svg","ranking":4,"value":4 },
    { id: "1-5 hearts",  "suite":"hearts","rank":"5",      "name":"5 hearts","img":"cards-front/hearts_5.svg","ranking":5,"value":5 },
    { id: "1-6 hearts",  "suite":"hearts","rank":"6",      "name":"6 hearts","img":"cards-front/hearts_6.svg","ranking":6,"value":6 },
    { id: "1-7 hearts",  "suite":"hearts","rank":"7",      "name":"7 hearts","img":"cards-front/hearts_7.svg","ranking":7,"value":7 },
    { id: "1-8 hearts",  "suite":"hearts","rank":"8",      "name":"8 hearts","img":"cards-front/hearts_8.svg","ranking":8,"value":8 },
    { id: "1-9 hearts",  "suite":"hearts","rank":"9",      "name":"9 hearts","img":"cards-front/hearts_9.svg","ranking":9,"value":9 },
    { id: "1-10 hearts",  "suite":"hearts","rank":"10",     "name":"10 hearts","img":"cards-front/hearts_10.svg","ranking":10,"value":10 },
    { id: "1-jack hearts",  "suite":"hearts","rank":"jack",   "name":"jack hearts","img":"cards-front/hearts_jack.svg","ranking":11,"value":10 },
    { id: "1-king hearts",  "suite":"hearts","rank":"king",   "name":"king hearts","img":"cards-front/hearts_king.svg","ranking":12,"value":10 },
    { id: "1-queen hearts",  "suite":"hearts","rank":"queen",  "name":"queen hearts","img":"cards-front/hearts_queen.svg","ranking":13,"value":10 },
    { id: "1-ace spades",  "suite":"spades","rank":"ace",    "name":"ace spades","img":"cards-front/spades_ace.svg","ranking":1,"value":1 },
    { id: "1-2 spades",  "suite":"spades","rank":"2",      "name":"2 spades","img":"cards-front/spades_2.svg","ranking":2,"value":2 },
    { id: "1-3 spades",  "suite":"spades","rank":"3",      "name":"3 spades","img":"cards-front/spades_3.svg","ranking":3,"value":3 },
    { id: "1-4 spades",  "suite":"spades","rank":"4",      "name":"4 spades","img":"cards-front/spades_4.svg","ranking":4,"value":4 },
    { id: "1-5 spades",  "suite":"spades","rank":"5",      "name":"5 spades","img":"cards-front/spades_5.svg","ranking":5,"value":5 },
    { id: "1-6 spades",  "suite":"spades","rank":"6",      "name":"6 spades","img":"cards-front/spades_6.svg","ranking":6,"value":6 },
    { id: "1-7 spades",  "suite":"spades","rank":"7",      "name":"7 spades","img":"cards-front/spades_7.svg","ranking":7,"value":7 },
    { id: "1-8 spades",  "suite":"spades","rank":"8",      "name":"8 spades","img":"cards-front/spades_8.svg","ranking":8,"value":8 },
    { id: "1-9 spades",  "suite":"spades","rank":"9",      "name":"9 spades","img":"cards-front/spades_9.svg","ranking":9,"value":9 },
    { id: "1-10 spades",  "suite":"spades","rank":"10",     "name":"10 spades","img":"cards-front/spades_10.svg","ranking":10,"value":10 },
    { id: "1-jack spades",  "suite":"spades","rank":"jack",   "name":"jack spades","img":"cards-front/spades_jack.svg","ranking":11,"value":10 },
    { id: "1-king spades",  "suite":"spades","rank":"king",   "name":"king spades","img":"cards-front/spades_king.svg","ranking":12,"value":10 },
    { id: "1-queen spades",  "suite":"spades","rank":"queen",  "name":"queen spades","img":"cards-front/spades_queen.svg","ranking":13,"value":10 },

    { id: "2-ace clubs",  "suite":"clubs", "rank":"ace",    "name":"ace clubs","img":"cards-front/clubs_ace.svg","ranking":1,"value":1 },
    { id: "2-2 clubs",  "suite":"clubs", "rank":"2",      "name":"2 clubs","img":"cards-front/clubs_2.svg","ranking":2,"value":2 },
    { id: "2-3 clubs",  "suite":"clubs", "rank":"3",      "name":"3 clubs","img":"cards-front/clubs_3.svg","ranking":3,"value":3 },
    { id: "2-4 clubs",  "suite":"clubs", "rank":"4",      "name":"4 clubs","img":"cards-front/clubs_4.svg","ranking":4,"value":4 },
    { id: "2-5 clubs",  "suite":"clubs", "rank":"5",      "name":"5 clubs","img":"cards-front/clubs_5.svg","ranking":5,"value":5 },
    { id: "2-6 clubs",  "suite":"clubs", "rank":"6",      "name":"6 clubs","img":"cards-front/clubs_6.svg","ranking":6,"value":6 },
    { id: "2-7 clubs",  "suite":"clubs", "rank":"7",      "name":"7 clubs","img":"cards-front/clubs_7.svg","ranking":7,"value":7 },
    { id: "2-8 clubs",  "suite":"clubs", "rank":"8",      "name":"8 clubs","img":"cards-front/clubs_8.svg","ranking":8,"value":8 },
    { id: "2-9 clubs",  "suite":"clubs", "rank":"9",      "name":"9 clubs","img":"cards-front/clubs_9.svg","ranking":9,"value":9 },
    { id: "2-10 clubs",  "suite":"clubs", "rank":"10",     "name":"10 clubs","img":"cards-front/clubs_10.svg","ranking":10,"value":10 },
    { id: "2-jack clubs",  "suite":"clubs", "rank":"jack",   "name":"jack clubs","img":"cards-front/clubs_jack.svg","ranking":11,"value":10 },
    { id: "2-king clubs",  "suite":"clubs", "rank":"king",   "name":"king clubs","img":"cards-front/clubs_king.svg","ranking":12,"value":10 },
    { id: "2-queen clubs",  "suite":"clubs", "rank":"queen",  "name":"queen clubs","img":"cards-front/clubs_queen.svg","ranking":13,"value":10 },
    { id: "2-ace diamonds",  "suite":"diamonds","rank":"ace",  "name":"ace diamonds","img":"cards-front/diamonds_ace.svg","ranking":1,"value":1 },
    { id: "2-2 diamonds",  "suite":"diamonds","rank":"2",    "name":"2 diamonds","img":"cards-front/diamonds_2.svg","ranking":2,"value":2 },
    { id: "2-3 diamonds",  "suite":"diamonds","rank":"3",    "name":"3 diamonds","img":"cards-front/diamonds_3.svg","ranking":3,"value":3 },
    { id: "2-4 diamonds",  "suite":"diamonds","rank":"4",    "name":"4 diamonds","img":"cards-front/diamonds_4.svg","ranking":4,"value":4 },
    { id: "2-5 diamonds",  "suite":"diamonds","rank":"5",    "name":"5 diamonds","img":"cards-front/diamonds_5.svg","ranking":5,"value":5 },
    { id: "2-6 diamonds",  "suite":"diamonds","rank":"6",    "name":"6 diamonds","img":"cards-front/diamonds_6.svg","ranking":6,"value":6 },
    { id: "2-7 diamonds",  "suite":"diamonds","rank":"7",    "name":"7 diamonds","img":"cards-front/diamonds_7.svg","ranking":7,"value":7 },
    { id: "2-8 diamonds",  "suite":"diamonds","rank":"8",    "name":"8 diamonds","img":"cards-front/diamonds_8.svg","ranking":8,"value":8 },
    { id: "2-9 diamonds",  "suite":"diamonds","rank":"9",    "name":"9 diamonds","img":"cards-front/diamonds_9.svg","ranking":9,"value":9 },
    { id: "2-10 diamonds",  "suite":"diamonds","rank":"10",   "name":"10 diamonds","img":"cards-front/diamonds_10.svg","ranking":10,"value":10 },
    { id: "2-jack diamonds",  "suite":"diamonds","rank":"jack", "name":"jack diamonds","img":"cards-front/diamonds_jack.svg","ranking":11,"value":10 },
    { id: "2-king diamonds",  "suite":"diamonds","rank":"king", "name":"king diamonds","img":"cards-front/diamonds_king.svg","ranking":12,"value":10 },
    { id: "2-queen diamonds",  "suite":"diamonds","rank":"queen","name":"queen diamonds","img":"cards-front/diamonds_queen.svg","ranking":13,"value":10 },
    { id: "2-ace hearts",  "suite":"hearts","rank":"ace",    "name":"ace hearts","img":"cards-front/hearts_ace.svg","ranking":1,"value":1 },
    { id: "2-2 hearts",  "suite":"hearts","rank":"2",      "name":"2 hearts","img":"cards-front/hearts_2.svg","ranking":2,"value":2 },
    { id: "2-3 hearts",  "suite":"hearts","rank":"3",      "name":"3 hearts","img":"cards-front/hearts_3.svg","ranking":3,"value":3 },
    { id: "2-4 hearts",  "suite":"hearts","rank":"4",      "name":"4 hearts","img":"cards-front/hearts_4.svg","ranking":4,"value":4 },
    { id: "2-5 hearts",  "suite":"hearts","rank":"5",      "name":"5 hearts","img":"cards-front/hearts_5.svg","ranking":5,"value":5 },
    { id: "2-6 hearts",  "suite":"hearts","rank":"6",      "name":"6 hearts","img":"cards-front/hearts_6.svg","ranking":6,"value":6 },
    { id: "2-7 hearts",  "suite":"hearts","rank":"7",      "name":"7 hearts","img":"cards-front/hearts_7.svg","ranking":7,"value":7 },
    { id: "2-8 hearts",  "suite":"hearts","rank":"8",      "name":"8 hearts","img":"cards-front/hearts_8.svg","ranking":8,"value":8 },
    { id: "2-9 hearts",  "suite":"hearts","rank":"9",      "name":"9 hearts","img":"cards-front/hearts_9.svg","ranking":9,"value":9 },
    { id: "2-10 hearts",  "suite":"hearts","rank":"10",     "name":"10 hearts","img":"cards-front/hearts_10.svg","ranking":10,"value":10 },
    { id: "2-jack hearts",  "suite":"hearts","rank":"jack",   "name":"jack hearts","img":"cards-front/hearts_jack.svg","ranking":11,"value":10 },
    { id: "2-king hearts",  "suite":"hearts","rank":"king",   "name":"king hearts","img":"cards-front/hearts_king.svg","ranking":12,"value":10 },
    { id: "2-queen hearts",  "suite":"hearts","rank":"queen",  "name":"queen hearts","img":"cards-front/hearts_queen.svg","ranking":13,"value":10 },
    { id: "2-ace spades",  "suite":"spades","rank":"ace",    "name":"ace spades","img":"cards-front/spades_ace.svg","ranking":1,"value":1 },
    { id: "2-2 spades",  "suite":"spades","rank":"2",      "name":"2 spades","img":"cards-front/spades_2.svg","ranking":2,"value":2 },
    { id: "2-3 spades",  "suite":"spades","rank":"3",      "name":"3 spades","img":"cards-front/spades_3.svg","ranking":3,"value":3 },
    { id: "2-4 spades",  "suite":"spades","rank":"4",      "name":"4 spades","img":"cards-front/spades_4.svg","ranking":4,"value":4 },
    { id: "2-5 spades",  "suite":"spades","rank":"5",      "name":"5 spades","img":"cards-front/spades_5.svg","ranking":5,"value":5 },
    { id: "2-6 spades",  "suite":"spades","rank":"6",      "name":"6 spades","img":"cards-front/spades_6.svg","ranking":6,"value":6 },
    { id: "2-7 spades",  "suite":"spades","rank":"7",      "name":"7 spades","img":"cards-front/spades_7.svg","ranking":7,"value":7 },
    { id: "2-8 spades",  "suite":"spades","rank":"8",      "name":"8 spades","img":"cards-front/spades_8.svg","ranking":8,"value":8 },
    { id: "2-9 spades",  "suite":"spades","rank":"9",      "name":"9 spades","img":"cards-front/spades_9.svg","ranking":9,"value":9 },
    { id: "2-10 spades",  "suite":"spades","rank":"10",     "name":"10 spades","img":"cards-front/spades_10.svg","ranking":10,"value":10 },
    { id: "2-jack spades",  "suite":"spades","rank":"jack",   "name":"jack spades","img":"cards-front/spades_jack.svg","ranking":11,"value":10 },
    { id: "2-king spades",  "suite":"spades","rank":"king",   "name":"king spades","img":"cards-front/spades_king.svg","ranking":12,"value":10 },
    { id: "2-queen spades",  "suite":"spades","rank":"queen",  "name":"queen spades","img":"cards-front/spades_queen.svg","ranking":13,"value":10 },

    { id: "1-joker", "suite":"joker","rank":"joker","name":"joker","img":"cards-front/joker_black.svg","ranking":25,"value":25 },
    { id: "2-joker", "suite":"joker","rank":"joker","name":"joker","img":"cards-front/joker_red.svg","ranking":25,"value":25 },
]